### PR TITLE
fix: added velodrome test

### PR DESCRIPTION
**Pull request by prathmeshkhandelwal1**
- Added `Valindrome Proposal`.

### CODE REVIEW

**Review by LayneHaber — APPROVED** [review]

**Comment by LayneHaber** [comment]
Need to add in RPC URLs for CI

**Review by LayneHaber — COMMENTED** [review]
see above comment re: ci

**Comment by prathmeshkhandelwal1** [comment]
> Need to add in RPC URLs for CI

Should I go ahead and atleast add for all mainnet networks?

**Comment by LayneHaber** [comment]
> > Need to add in RPC URLs for CI
> 
> Should I go ahead and atleast add for all mainnet networks?

Yes, but not any of the ones we actually use in production environments. Can be all free-tier. May make CI finicky, but we can deal with that

**Comment by prathmeshkhandelwal1** [comment]
> > > Need to add in RPC URLs for CI
> > 
> > 
> > Should I go ahead and atleast add for all mainnet networks?
> 
> Yes, but not any of the ones we actually use in production environments. Can be all free-tier. May make CI finicky, but we can deal with that

Sure, Can you give me permissions on this repo, so that I can open settings here and configure env there.

**Pull request merged**
